server:
  port: ${API_PORT:8000}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:Caijinwei%262026@103.236.97.248:27017/yanjing?authSource=admin}
    redis:
      host: ${REDIS_HOST:103.236.97.248}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:Caijinwei&2026}

management:
  endpoints:
    web:
      exposure:
        include: health,info
